spring:
  datasource:
    url: jdbc:mysql://192.168.146.3:3306/atcrowdfunding
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    # 指定数据库连接池的类型
    type: com.alibaba.druid.pool.DruidDataSource
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
    