#
spring:
  application:
    name: cloud-consumer-user

#
server:
  port: 9000
  
#
eureka:
  client:
    service-url:
      defaultZont: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true